[build]
  publish = "public"
  command = "npm run build"

[dev]
  command = "npm run start"

[functions]
  directory = "netlify-functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200